# ESLint
#
#   Configuration: http://eslint.org/docs/user-guide/configuring
#   Rules: http://eslint.org/docs/rules/

---
env:
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

globals:
  Promise: true
  BufferEncoding: readonly

rules:
  valid-jsdoc:
    [2, { "requireReturn": false, "prefer": { "return": "returns" } }]
  "@typescript-eslint/no-explicit-any": "off"
